#!/bin/sh

filter_type="$1"

get_conf_value () {
  local conf="$1"
  local key="$2"

  printf "$conf" | grep "^$key"
}

sed_escape () {
  echo "$1" | sed -e 's/[\/&]/\\&/g'
}

if [ ! -f ./secrets ]; then
  echo "secrets file not found in project root!" 1>&2
  exit 1
fi

secrets="$(awk -F ' *= *' 'length() {gsub(/^ *| *$/, ""); $1=$1; print $1 "=" $2}' ./secrets)"

SED_CMD="sed $(echo "$secrets" | while read -r line; do
  key="$(printf "$line" | awk -F = '{print $1}')"
  value="$(printf "$line" | awk -F = '{print $2}')"
  escaped_key="$(sed_escape "$key")"
  escaped_value="$(sed_escape "$value")"

  if [ $filter_type = "clean" ]; then
    arg="-e 's/$escaped_value/{$escaped_key}/' "
  elif [ $filter_type = "smudge" ]; then
    arg="-e 's/{$escaped_key}/$escaped_value/' "
  fi

  printf -- "$arg"
done)"

eval "$SED_CMD"
